repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: pants-fmt
        name: pants fmt
        entry: ./pants fmt --changed-since=HEAD
        language: system
        types: [python]
        pass_filenames: false

      - id: pants-lint
        name: pants lint
        entry: ./pants lint --changed-since=HEAD
        language: system
        types: [python]
        pass_filenames: false

      - id: pants-check
        name: pants check (mypy)
        entry: ./pants check --changed-since=HEAD
        language: system
        types: [python]
        pass_filenames: false

      - id: pants-test
        name: pants test
        entry: ./pants test --changed-since=HEAD
        language: system
        types: [python]
        pass_filenames: false
